# ===================================================================
# Spring Boot Configuration
# ===================================================================
server:
  port: 8085

azure:
  keyvault:
    uri: https://cysiz-kv-eastus.vault.azure.net/
    pfxCertificate: CYSIZ-PFX-CERT
    azureCertificate: CYSIZ-AZURE-CERT
    keyIdentifier: ${azure.keyvault.uri}/keys/CYSIZ-RSA-KEY






