# ===================================================================
# Spring Boot Configuration
# ===================================================================

# Application Context Path & Name
server:
  servlet:
    context-path: /forescout-keyvault-service

spring:
  main:
    allow-bean-definition-overriding: false
  application:
    name :  forescout-keyvault-service

# CosmosDB for Postgres Datasource Configuration(s) - Azure KeyVault Secret(s)
  datasource:
    url: ${CYSIZ-PG-DB-URL}
    username: ${CYSIZ-PG-DB-USER}
    password: ${CYSIZ-PG-DB-PSWD}
    driver-class-name: org.postgresql.Driver

    jpa:
      show-sql: true
      hibernate.ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          default_schema: keyvault

# Azure KeyVault Configuration
  cloud:
    azure:
      keyvault:
        uri: ${AZURE_KEYVAULT_URI}
        enabled: true
        secret:
          property-source-enabled: true
          property-sources:
            - endpoint: ${AZURE_KEYVAULT_URI}

# Azure Certificate, Private Key and Sign Key Secrets
azure:
  keyvault:
    uri: ${AZURE_KEYVAULT_URI}
    pfxCertificate: ${CYSIZ-PFX-CERT-NAME}
    azureCertificate: ${CYSIZ-AZURE-CERT-NAME}
    keyIdentifier: ${CYSIZ-RSA-KEY-ID}
    jwtSecretSignKey: ${JWT-TOKEN-SIGN-KEY}

# Logging
logging:
  level:
    com.forescout.cysiv: DEBUG
    com.azure.security.keyvault: info
    com.azure.identity: info
    org.springframework.boot: DEBUG