# ===================================================================
# Spring Boot Configuration
# ===================================================================
server:
  port: 8080

azure:
  keyvault:
    uri: https://cysiz-kv-eastus.vault.azure.net


