# ===================================================================
# Spring Boot Configuration
# ===================================================================
server:
  servlet:
    context-path: /forescout-keyvault-service

spring:
  application:
    name :  forescout-keyvault-service

#  cloud:
#    azure:
#      keyvault:
#        secret:
#          property-sources[0]:
#            endpoint: ${azure.keyvault.uri}
